#path to dataset, need modification if necessary
DATASET:
  PATH: ./supervised/Agriculture-Vision-2021/

# path to save the model, need modification if necessary
EXPERIMENT:
  SAVER:
    DIRPATH: ./models/

# The trainer setting, each node in our cluster has 4 2080Ti GPU.
# This model requires 8 GPUs in total, so set GPUS=4 and NUM_NODES=2.
# If 4 GPUs is used for reproduction, delete NUM_NODES lines and modify MAX_STEPS.
TRAINER:
  MAX_STEPS: 150000
  GPUS: 4
  ACCELERATOR: ddp
  SYNC_BATCHNORM: true
  NUM_NODES: 2

DATALOADER:
  BATCH_SIZE:
    TRAIN: 2
    TEST: 2
    VAL: 2
  INCLUDE_VALID: true

MODEL:
  ENCODER: efficientnet-b5
  VERSION: DeepLabV3Plus

SEED: 2021
