# path to dataset, need modification if necessary
DATASET:
  PATH: ./supervised/Agriculture-Vision-2021/

# path to save the model, need modification if necessary
EXPERIMENT:
  SAVER:
    DIRPATH: ./models/

# The trainer setting, our cluster have 4 2080Ti GPU
# This model require 4 GPUs in total, so set GPUS=4
TRAINER:
  MAX_STEPS: 150000
  GPUS: 4
  ACCELERATOR: ddp
  SYNC_BATCHNORM: true

DATALOADER:
  BATCH_SIZE:
    TRAIN: 4
    TEST: 4
    VAL: 4
  INCLUDE_VALID: true

MODEL:
  ENCODER: efficientnet-b3
  VERSION: DeepLabV3Plus

SEED: 3532
